version: '3'

services:
  composer:
    image: composer:latest

  app:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ../:/app
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - .env

  nginx:
    image: nginx:1.19.7
    command: [nginx, '-g', 'daemon off;']
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
